name: ARM Template Build and Test

on: push

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        bicepFilePath: [ 'biceps/sample3.bicep biceps/sample4.bicep' ]
        outputFilePath: [  'biceps/sample3.json biceps/sample4.json' ]

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Run the private action
      uses: Azure/bicep-build-action@main
      with:
        bicepFilePath:'biceps/sample3.bicep'
        outputFilePath:'biceps/sample3.json'

